///////////////////////////////////////
// Copyright (C) 2004 Robert P. Wolf //
//        ALL RIGHTS RESERVED        //
///////////////////////////////////////

#ifndef _VA_GLOBAL_SWITCHES
#define _VA_GLOBAL_SWITCHES

//#define _RETAIL
#define _PRIVATE
//#define _DOWNLOAD_FULL
//#define _DOWNLOAD_ALARM
//#define _DOWNLOAD_MICRO
//#define _DOWNLOAD_POLY
//#define _DOWNLOAD_CLASSIC

#ifdef _RETAIL
#define ALARM_SERIAL_HEADER "TC"
#define MICRO_SERIAL_HEADER "TC"
#define POLY_SERIAL_HEADER "TC"
#define CLASSIC_SERIAL_HEADER "TC"
#define ALARM_SERIAL_SHIFT 46
#define MICRO_SERIAL_SHIFT 46
#define POLY_SERIAL_SHIFT 46
#define CLASSIC_SERIAL_SHIFT 46
#define SECURITY_CRASH_AFTER 10
#define DISTRIBUTION_ID_PRESENT true
#define VOLUME_ID_PRESENT true
#endif

#ifdef _DOWNLOAD_FULL
#define ALARM_SERIAL_HEADER "AP"
#define MICRO_SERIAL_HEADER "AP"
#define POLY_SERIAL_HEADER "AP"
#define CLASSIC_SERIAL_HEADER "AP"
#define ALARM_SERIAL_SHIFT 41
#define MICRO_SERIAL_SHIFT 41
#define POLY_SERIAL_SHIFT 41
#define CLASSIC_SERIAL_SHIFT 41
#define SECURITY_CRASH_AFTER 600
#define DISTRIBUTION_ID_PRESENT false
#define VOLUME_ID_PRESENT true
#endif

#ifdef _DOWNLOAD_ALARM
#define ALARM_SERIAL_HEADER "AA"
#define MICRO_SERIAL_HEADER "AA"
#define POLY_SERIAL_HEADER "AA"
#define CLASSIC_SERIAL_HEADER "AA"
#define ALARM_SERIAL_SHIFT 17
#define MICRO_SERIAL_SHIFT 17
#define POLY_SERIAL_SHIFT 17
#define CLASSIC_SERIAL_SHIFT 17
#define SECURITY_CRASH_AFTER 10
#define DISTRIBUTION_ID_PRESENT false
#define VOLUME_ID_PRESENT true
#endif

#ifdef _PRIVATE
#define ALARM_SERIAL_HEADER "CV"
#define MICRO_SERIAL_HEADER "CV"
#define POLY_SERIAL_HEADER "CV"
#define CLASSIC_SERIAL_HEADER "CV"
#define ALARM_SERIAL_SHIFT 0
#define MICRO_SERIAL_SHIFT 0
#define POLY_SERIAL_SHIFT 0
#define CLASSIC_SERIAL_SHIFT 0
#define SECURITY_CRASH_AFTER 10
#define DISTRIBUTION_ID_PRESENT false
#define VOLUME_ID_PRESENT false
#endif




#define RETAIL_DISTRIBUTION_ID "TC-000000-11"
#define ALARM_DISTRIBUTION_ID "AA-000000-FC"
#define MICRO_DISTRIBUTION_ID "AM-000000-08"
#define POLY_DISTRIBUTION_ID "AL-000000-07"
#define CLASSIC_DISTRIBUTION_ID "AC-000000-FE"
#define VA_PACK_DISTRIBUTION_ID "AP-000000-0B"
#define PRIVATE_DISTRIBUTION_ID "CV-000000-13"


#endif